In [1]:
import torch
import torch.nn.functional as F
import requests
from PIL import Image
from transformers import AutoProcessor, LlavaForConditionalGeneration
from transformers import BitsAndBytesConfig
# from datasets import load_dataset

import matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm
import logging
logger = logging.getLogger(__name__)

func_to_enable_grad = '_sample'
setattr(LlavaForConditionalGeneration, func_to_enable_grad, torch.enable_grad(getattr(LlavaForConditionalGeneration, func_to_enable_grad)))

C:\Users\PRYth\anaconda3\envs\fyp\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
C:\Users\PRYth\anaconda3\envs\fyp\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_id = "llava-hf/llava-1.5-7b-hf"
quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    offload_state_dict=True
)
model = LlavaForConditionalGeneration.from_pretrained(
    model_id, 
    torch_dtype=torch.float16, 
    low_cpu_mem_usage=True, 
    quantization_config=quant_config,
    attn_implementation = "eager"
).to(0)

#--------------------------------------------------
model.vision_tower.config.output_attentions = True

# set hooks to get attention weights
model.enc_attn_weights = []
#outputs: attn_output, attn_weights, past_key_value
def forward_hook(module, inputs, output): 
    if output[1] is None:
        logger.error(
            ("Attention weights were not returned for the encoder. "
            "To enable, set output_attentions=True in the forward pass of the model. ")
        )
        return output
    
    output[1].requires_grad_(True)
    output[1].retain_grad()
    model.enc_attn_weights.append(output[1].detach().cpu())
    return output

hooks_pre_encoder, hooks_encoder = [], []
for layer in model.language_model.layers:
    hook_encoder_layer = layer.self_attn.register_forward_hook(forward_hook)
    hooks_pre_encoder.append(hook_encoder_layer)

model.enc_attn_weights_vit = []

def forward_hook_image_processor(module, inputs, output): 
    if output[1] is None:
        logger.warning(
            ("Attention weights were not returned for the vision model. "
             "Relevancy maps will not be calculated for the vision model. " 
             "To enable, set output_attentions=True in the forward pass of vision_tower. ")
        )
        return output

    output[1].requires_grad_(True)
    output[1].retain_grad()
    model.enc_attn_weights_vit.append(output[1])
    return output

hooks_pre_encoder_vit = []
for layer in model.vision_tower.vision_model.encoder.layers:
    hook_encoder_layer_vit = layer.self_attn.register_forward_hook(forward_hook_image_processor)
    hooks_pre_encoder_vit.append(hook_encoder_layer_vit)

# add in hooks to extract/modify the hidden states

model.extracted_hidden_states = []

def forward_hook_hidden_states(module, inputs, output):
    if output is None:
        logger.warning(
            ("Unable to extract hidden states. ")
        )
        return output

    output.requires_grad_(True)
    output.retain_grad()
    # output[0, -2, 2789] = 500
    # output[0, -2, 2608] = 500
    model.extracted_hidden_states.append(output)
    return output

hook_handle = model.language_model.layers[13].register_forward_hook(forward_hook_hidden_states)

# Storage dictionary for results
model.lm_qkv_vectors = {}

def make_hook(name, num_heads, head_dim):
    def hook_fn(module, input, output):
        """
        module: the Linear4bit projection (q_proj, k_proj, or v_proj)
        output: tensor [batch_size, seq_len, hidden_dim]
        """
        bsz, seq_len, hidden_dim = output.shape

        # Reshape to separate heads: [batch, num_heads, seq_len, head_dim]
        reshaped = (
            output.view(bsz, seq_len, num_heads, head_dim)
                  .transpose(1, 2)
                  .detach()
                  .cpu()
        )

        model.lm_qkv_vectors[name] = reshaped
    return hook_fn


hooks_lm_qkv = []

# Loop through each decoder layer in the language model
for i, layer in enumerate(model.language_model.layers):
    attn = layer.self_attn
    # Derive number of heads and head dimension robustly
    hidden_size = attn.q_proj.in_features  # e.g. 4096
    out_features = attn.q_proj.out_features  # also 4096
    # try to get from attn if available, else fallback
    num_heads = getattr(attn, "num_heads", None)
    if num_heads is None:
        # For LLaMA, you can find it in attn.num_key_value_heads or attn.num_attention_heads sometimes
        num_heads = getattr(attn, "num_attention_heads", getattr(attn, "num_key_value_heads", 32))
    head_dim = out_features // num_heads

    for proj_name in ['q_proj', 'k_proj', 'v_proj']:
        module = getattr(attn, proj_name)
        hook = module.register_forward_hook(
            make_hook(f"layer_{i}_{proj_name}", num_heads, head_dim)
        )
        hooks_lm_qkv.append(hook)

#--------------------------------------------------

processor = AutoProcessor.from_pretrained(model_id)

if model.language_model.config.model_type == "gemma":
    eos_token_id = processor.tokenizer('<end_of_turn>', add_special_tokens=False).input_ids[0]
else:
    eos_token_id = processor.tokenizer.eos_token_id

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:24<00:00,  8.09s/it]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [3]:
model

LlavaForConditionalGeneration(
  (model): LlavaModel(
    (vision_tower): CLIPVisionModel(
      (vision_model): CLIPVisionTransformer(
        (embeddings): CLIPVisionEmbeddings(
          (patch_embedding): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
          (position_embedding): Embedding(577, 1024)
        )
        (pre_layrnorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (encoder): CLIPEncoder(
          (layers): ModuleList(
            (0-23): 24 x CLIPEncoderLayer(
              (self_attn): CLIPAttention(
                (k_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                (v_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                (q_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
                (out_proj): Linear4bit(in_features=1024, out_features=1024, bias=True)
              )
              (layer_norm1): LayerNorm((1024,), eps=1e-05, elementwise_affi

In [4]:
# tokens = torch.load("full_generation.pt").tolist()
# # Decode each token individually
# decoded_tokens = [processor.decode([t]) for t in tokens]

# # Optionally, print
# for i, tok in enumerate(decoded_tokens):
#     print(f"{i}: {repr(tok)}")

In [5]:
# file = r"saved/vit_attn"
# import os
# torch.save(tokens, os.path.join(file, "lmao.pt"))

In [6]:
conversation = [
    {
      "role": "user",
      "content": [
          {"type": "text", "text": "Is this a plane?"},
          {"type": "image"},
        ],
    },
]
conv_step = conversation + [
    {"role": "assistant", "content": [{"type": "text", "text": "Yes, this is a"}]}
]
conv_step

[{'role': 'user',
  'content': [{'type': 'text', 'text': 'Is this a plane?'},
   {'type': 'image'}]},
 {'role': 'assistant',
  'content': [{'type': 'text', 'text': 'Yes, this is a'}]}]

In [5]:
image_file = r"C:\Users\PRYth\Downloads\02\data\11ALRZB7K00VqpzlD.jpg"
raw_image = Image.open(image_file).convert("RGB")
prompt_appended = processor.apply_chat_template(conv_step, add_generation_prompt=False, return_tensors="pt")
inputs_appended = processor(images=raw_image, text=prompt_appended, return_tensors='pt').to(0, torch.float16)

output_appended = model(**inputs_appended,
                        use_cache=False,
                        output_attentions=True,
                        output_hidden_states=True,
                        return_dict_in_generate=True,
                        output_scores=True,
                        eos_token_id=eos_token_id)
print(len(model.enc_attn_weights))

32


In [8]:
model.lm_qkv_vectors

{'layer_0_q_proj': tensor([[[[ 9.0820e-02, -2.7930e-01,  5.7812e-01,  ..., -2.7188e+00,
             1.4688e+00, -2.0898e-01],
           [ 2.0905e-03, -1.2344e+00,  1.9141e+00,  ..., -7.3047e-01,
             5.0391e-01, -9.1797e-01],
           [ 4.0039e-01, -8.2812e-01,  1.8750e+00,  ..., -8.9844e-01,
             8.2422e-01, -1.0000e+00],
           ...,
           [-8.5449e-03, -5.8984e-01,  1.2188e+00,  ..., -6.4062e-01,
             3.7695e-01, -7.5781e-01],
           [ 5.3711e-02, -6.4844e-01,  1.2812e+00,  ..., -5.8984e-01,
             3.7695e-01, -7.2656e-01],
           [-5.9326e-02, -2.7539e-01,  8.9844e-01,  ..., -4.2773e-01,
             1.2061e-01, -5.7031e-01]],
 
          [[-1.2598e-01,  2.2949e-01, -5.0391e-01,  ...,  4.1211e-01,
            -5.3906e-01,  4.4727e-01],
           [ 2.0410e-01,  1.7285e-01, -5.4297e-01,  ...,  7.1289e-02,
            -4.2188e-01,  1.3184e-01],
           [ 1.3672e-01, -3.0518e-02, -9.3359e-01,  ...,  1.9434e-01,
            -3.7109e-

In [12]:
model.lm_qkv_vectors["layer_0_q_proj"].shape

torch.Size([1, 32, 599, 128])

In [19]:
TOKENS_NOT_OF_INTERESTS = ["<s>", "US", "ER", ":", "", "\n", "!", "?", ".", ":", ",", " ", "A", "SS", "IST", "ANT"]

In [20]:
decoded_input_tokens = [processor.decode([t]) for t in inputs_appended["input_ids"][0]]

# Optionally, print
for i, tok in enumerate(decoded_input_tokens):
    print(f"{i}: {repr(tok)}")

0: '<s>'
1: 'US'
2: 'ER'
3: ':'
4: ''
5: '<image>'
6: '<image>'
7: '<image>'
8: '<image>'
9: '<image>'
10: '<image>'
11: '<image>'
12: '<image>'
13: '<image>'
14: '<image>'
15: '<image>'
16: '<image>'
17: '<image>'
18: '<image>'
19: '<image>'
20: '<image>'
21: '<image>'
22: '<image>'
23: '<image>'
24: '<image>'
25: '<image>'
26: '<image>'
27: '<image>'
28: '<image>'
29: '<image>'
30: '<image>'
31: '<image>'
32: '<image>'
33: '<image>'
34: '<image>'
35: '<image>'
36: '<image>'
37: '<image>'
38: '<image>'
39: '<image>'
40: '<image>'
41: '<image>'
42: '<image>'
43: '<image>'
44: '<image>'
45: '<image>'
46: '<image>'
47: '<image>'
48: '<image>'
49: '<image>'
50: '<image>'
51: '<image>'
52: '<image>'
53: '<image>'
54: '<image>'
55: '<image>'
56: '<image>'
57: '<image>'
58: '<image>'
59: '<image>'
60: '<image>'
61: '<image>'
62: '<image>'
63: '<image>'
64: '<image>'
65: '<image>'
66: '<image>'
67: '<image>'
68: '<image>'
69: '<image>'
70: '<image>'
71: '<image>'
72: '<image>'
73: '<image>'
7

In [21]:
for i, j in enumerate(decoded_input_tokens):
    if j in TOKENS_NOT_OF_INTERESTS:
        continue
    else:
        print(f"{i} {decoded_input_tokens[i]}")

5 <image>
6 <image>
7 <image>
8 <image>
9 <image>
10 <image>
11 <image>
12 <image>
13 <image>
14 <image>
15 <image>
16 <image>
17 <image>
18 <image>
19 <image>
20 <image>
21 <image>
22 <image>
23 <image>
24 <image>
25 <image>
26 <image>
27 <image>
28 <image>
29 <image>
30 <image>
31 <image>
32 <image>
33 <image>
34 <image>
35 <image>
36 <image>
37 <image>
38 <image>
39 <image>
40 <image>
41 <image>
42 <image>
43 <image>
44 <image>
45 <image>
46 <image>
47 <image>
48 <image>
49 <image>
50 <image>
51 <image>
52 <image>
53 <image>
54 <image>
55 <image>
56 <image>
57 <image>
58 <image>
59 <image>
60 <image>
61 <image>
62 <image>
63 <image>
64 <image>
65 <image>
66 <image>
67 <image>
68 <image>
69 <image>
70 <image>
71 <image>
72 <image>
73 <image>
74 <image>
75 <image>
76 <image>
77 <image>
78 <image>
79 <image>
80 <image>
81 <image>
82 <image>
83 <image>
84 <image>
85 <image>
86 <image>
87 <image>
88 <image>
89 <image>
90 <image>
91 <image>
92 <image>
93 <image>
94 <image>
95 <image>
96 <

In [7]:
print(output_appended.logits.shape)
# Decode them
topk = torch.topk(output_appended.logits[:, -2], k=5, dim=-1)
for ids in topk.indices:
    print(processor.tokenizer.decode(ids))

torch.Size([1, 599, 32064])
plane large white jet commercial


In [9]:
for i in range(33):
    print(i)
    hidden_state = output_appended.hidden_states[i]
    logits_from_hidden_state = model.lm_head(hidden_state)
    
    # Decode them
    topk = torch.topk(logits_from_hidden_state[:, -2], k=10, dim=-1)
    for ids in topk.indices:
        for j in ids:
            print(processor.tokenizer.decode(j))
        print(topk.values)
    print("---------------------")

0
eros
EDIT
versary
ǔ
partment
ids
usammen
sess
ims
irt
tensor([[0.0544, 0.0498, 0.0487, 0.0482, 0.0476, 0.0474, 0.0474, 0.0461, 0.0450,
         0.0449]], device='cuda:0', dtype=torch.float16,
       grad_fn=<TopkBackward0>)
---------------------
1
in
.
(
for
…
bolds


to
Sito
and
tensor([[0.2642, 0.2229, 0.2225, 0.2188, 0.2148, 0.2125, 0.1987, 0.1975, 0.1958,
         0.1879]], device='cuda:0', dtype=torch.float16,
       grad_fn=<TopkBackward0>)
---------------------
2
❯
in
➖
on
to
bolds
Bedeut
partment
sterd
for
tensor([[0.2115, 0.1996, 0.1964, 0.1935, 0.1924, 0.1892, 0.1868, 0.1826, 0.1823,
         0.1802]], device='cuda:0', dtype=torch.float16,
       grad_fn=<TopkBackward0>)
---------------------
3
➖
‭
frak
̲
kin
bolds
totalité
≫
❯
Zyg
tensor([[0.3838, 0.3293, 0.3210, 0.3171, 0.3037, 0.2930, 0.2852, 0.2837, 0.2837,
         0.2788]], device='cuda:0', dtype=torch.float16,
       grad_fn=<TopkBackward0>)
---------------------
4
➖
‭
̀
to
demselben
frak
in
for
guez
bolds
tensor([[0

In [ ]:
def attention_rollout(attn_maps):
    """
    Performs rollout on the provided attention maps. Pass in the model attn weights e.g. model.enc_attn_weights[0:32]
    """
    attn_rollout = []
    device = attn_maps[0].device
    batch_size, _, seq_len, _ = attn_maps[0].shape
    
    # Identity matrix for self-attention
    I = torch.eye(seq_len, device=device).unsqueeze(0).expand(batch_size, seq_len, seq_len)

    prod = I.clone()
    
    for i, attn_map in enumerate(attn_maps):
        # Average over heads → [batch, seq_len, seq_len]
        attn_map = attn_map.mean(dim=1)
        
        # Add identity and multiply
        prod = prod @ (attn_map + I)
        
        # Normalize across sequence dimension
        prod = prod / prod.sum(dim=-1, keepdim=True)
        
        attn_rollout.append(prod)

    return attn_rollout

In [ ]:
rollout = attention_rollout(model.enc_attn_weights[0:32])
final_rollout = rollout[-1]
print(final_rollout.shape)

In [ ]:
seq_len = final_rollout.shape[1]
valid_range = range(1, seq_len)  # skip token 0
token_importances = final_rollout[0, -2, valid_range]  # importance of all tokens for position t
topk = 400
values, indices = torch.topk(token_importances, k=topk)
for score, idx in zip(values.tolist(), indices.tolist()):
    if idx >= 5 and idx <= 580:
        continue
    print(f"Token {idx} → importance {score}")


In [ ]:
last_attn = model.enc_attn_weights[-1].mean(dim=1)  # [batch, seq_len, seq_len]
length = last_attn.shape[1]
token_importances = last_attn[0, length-2]    # attention from t → all tokens
topk = 100
values, indices = torch.topk(token_importances, k=topk)
for score, idx in zip(values.tolist(), indices.tolist()):
    print(f"Token {idx} → importance {score}")

## Generate heatmap of important image tokens from rollout

In [ ]:
import numpy as np
import torch 

rollout = attention_rollout(model.enc_attn_weights[0:32])
final_rollout = rollout[-1]
print(final_rollout.shape)
token_importances = final_rollout[0, -2]  # importance of all tokens for position t
topk = 50
values, indices = torch.topk(token_importances, k=topk)
heatmap_raw = [0 for i in range(576)]
for score, idx in zip(values.tolist(), indices.tolist()):
    if idx >= 5 and idx <= 580:
        heatmap_raw[idx-5] = 1
    else:
        print(idx)

import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

cls_attn = torch.tensor(heatmap_raw)
H, W = 24, 24  # 336 / 14
heatmap = cls_attn.reshape(H, W).detach().cpu().numpy()

# Assuming heatmap shape [H, W]
heatmap_tensor = torch.tensor(heatmap[None, None], dtype=torch.float32)
heatmap_full = F.interpolate(heatmap_tensor, size=(raw_image.size[1], raw_image.size[0]), mode='area')[0,0].numpy()

image = Image.open(image_file).convert("RGB")
plt.imshow(image)
plt.imshow(heatmap_full, cmap='jet', alpha=0.5)
plt.axis('off')
plt.colorbar()
plt.show()

## Generate heatmap of important image tokens from last attention block

In [ ]:
last_attn = model.enc_attn_weights[-1].mean(dim=1)  # [batch, seq_len, seq_len]
length = last_attn.shape[1]
token_importances = last_attn[0, length-1]    # attention from t → all tokens
topk = 50
values, indices = torch.topk(token_importances, k=topk)
heatmap_raw = [0 for i in range(576)]
for score, idx in zip(values.tolist(), indices.tolist()):
    if idx >= 5 and idx <= 580:
        heatmap_raw[idx-5] = 1
    else:
        print(idx)

cls_attn = torch.tensor(heatmap_raw)
H, W = 24, 24  # 336 / 14
heatmap = cls_attn.reshape(H, W).detach().cpu().numpy()

# Assuming heatmap shape [H, W]
heatmap_tensor = torch.tensor(heatmap[None, None], dtype=torch.float32)
heatmap_full = F.interpolate(heatmap_tensor, size=(raw_image.size[1], raw_image.size[0]), mode='nearest')[0,0].numpy()

image = Image.open(image_file).convert("RGB")
plt.imshow(image)
plt.imshow(heatmap_full, cmap='jet', alpha=0.5)
plt.axis('off')
plt.show()

# Mechanistic Interpretability

In [ ]:
model.extracted_hidden_states[0]

In [ ]:
output_appended.hidden_states[14]

In [ ]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

hidden_state = output_appended.hidden_states[14][0][-2]
print(hidden_state.shape)
H, W = 64, 64  # 336 / 14
heatmap = hidden_state.reshape(H, W).detach().cpu().numpy()

# Assuming heatmap shape [H, W]
heatmap_tensor = torch.tensor(heatmap[None, None], dtype=torch.float32)
heatmap_full = F.interpolate(heatmap_tensor, size=(64, 64), mode='nearest-exact')[0,0].numpy()

plt.imshow(heatmap_full, cmap='jet', alpha=0.75)
plt.axis('off')
plt.colorbar()
plt.show()

In [ ]:
topk = torch.topk(hidden_state, k=5, dim=-1)
for ids in topk.indices:
    print(f"{ids}")
print(topk.values)

In [ ]:
topk = torch.topk(hidden_state, k=5, dim=-1, largest=False)
for ids in topk.indices:
    print(f"{ids}")
print(topk.values)